import { AIProvider } from './AIProvider.js';

const RED_FLAG_KEYWORDS = [
  'chest pain', 'heart attack', 'shortness of breath', 'difficulty breathing',
  'sudden numbness', 'facial drooping', 'arm weakness', 'slurred speech',
  'stroke', 'severe bleeding', 'unconscious', 'loss of consciousness',
  'severe head trauma', 'sudden vision loss', 'coughing blood', 'anaphylaxis'
];

export class FallbackProvider extends AIProvider {
  constructor() {
    super('FallbackProvider');
  }

  isAvailable() {
    return true; // Always available
  }

  async analyzeSymptoms(symptoms, vitalSigns = null) {
    const lower = (symptoms || '').toLowerCase();
    const detectedRedFlags = RED_FLAG_KEYWORDS.filter(k => lower.includes(k));
    const isCritical = detectedRedFlags.length > 0;

    return {
      severity: isCritical ? 'critical' : 'medium',
      urgency: isCritical ? 'emergency' : 'routine',
      symptoms_detected: symptoms ? symptoms.split(',').map(s => s.trim()) : ['General Discomfort'],
      possible_categories: isCritical ? ['Emergency Medicine / Cardiology'] : ['General Health Assessment'],
      recommended_next_step: isCritical
        ? 'SEEK IMMEDIATE EMERGENCY CARE (Call 911 or visit Nearest Emergency Room)'
        : 'Schedule a telehealth consultation with a verified MediConnect doctor.',
      red_flags: detectedRedFlags.map(f => `Emergency flag detected: ${f}`),
      confidence: 0.90,
      disclaimer: 'This assessment is generated by MediConnect AI Triage Safety Engine for guidance only. Consult a doctor for medical diagnosis.',
      model_info: { provider: this.name, model: 'deterministic-rules-engine-v2', timestamp: new Date().toISOString() }
    };
  }

  async analyzeConsultation(chatHistory) {
    return `### Clinical Consultation Summary (Fallback Engine)\n\n**Key Observations:** Patient reported symptoms and discussed treatment options.\n\n**Recommendation:** Follow up with primary healthcare provider if symptoms persist.`;
  }

  async getAIChatResponse(messages) {
    const last = messages[messages.length - 1]?.content || '';
    return `I have reviewed your inquiry regarding "${last.substring(0, 50)}...". Please consult your treating physician for personalized medical advice. If you experience severe pain or emergency symptoms, seek immediate emergency care.`;
  }
}
